### ISSUE TITLE
Error when I try to create a schema

### ISSUE THREAD

**Issue by Ananiaslitz** [leocavalcante/hyperf-doctrine#1]
/opt/www # vendor/bin/doctrine orm:schema-tool:create
sf
PHP Fatal error:  Uncaught RuntimeException: Setup tool cannot configure caches without doctrine/cache 1.11 or symfony/cache. Please add an explicit dependency to either library. in /opt/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php:193

**Comment by leocavalcante** [comment]
You have to install either doctrine/cache or symfony/cache. It is a Doctrine requirement https://github.com/doctrine/orm/issues/8809
